namespace Ocsf.Generator;

/// <summary>What kind of type a set of attributes is being emitted into.</summary>
internal enum EmitTarget
{
    /// <summary>An OCSF object: every attribute is emitted.</summary>
    Object,

    /// <summary>The OcsfEvent base partial: enum attributes are left to concrete classes,
    /// classification attributes are emitted as plain numbers.</summary>
    BaseEvent,

    /// <summary>A concrete event class: attributes declared identically on base_event are
    /// skipped; enum attributes are always emitted with per-class enum types.</summary>
    EventClass,
}

public static class Emitter
{
    /// <summary>Directories owned entirely by the generator, relative to the repo root.</summary>
    public static readonly string[] OutputRoots =
    [
        "src/Ocsf/Generated",
        "src/Ocsf.Validation/Generated",
    ];

    /// <summary>Classification attributes stay plain numbers; their single-value enums carry
    /// the class identity, which the generator surfaces as constants instead.</summary>
    internal static readonly HashSet<string> ClassificationAttrs = ["class_uid", "category_uid", "type_uid"];

    public static IReadOnlyList<(string RelativePath, string Content)> EmitAll(ExportSchema schema)
    {
        var mapper = new TypeMapper(schema);
        var outputs = new List<(string, string)>();

        foreach (var (name, obj) in schema.Objects.OrderBy(o => o.Key, StringComparer.Ordinal))
        {
            var pascal = NameMapper.PascalCase(name);
            outputs.Add(($"src/Ocsf/Generated/Objects/{pascal}.g.cs", EmitObject(schema, mapper, name, obj)));
        }

        outputs.Add(("src/Ocsf/Generated/OcsfEvent.g.cs", EmitBaseEvent(schema, mapper)));

        foreach (var (name, cls) in schema.Classes.OrderBy(c => c.Key, StringComparer.Ordinal))
        {
            var pascal = NameMapper.PascalCase(name);
            var category = CategoryNamespace(cls.Category);
            outputs.Add(($"src/Ocsf/Generated/Events/{category}/{pascal}.g.cs", EmitEventClass(schema, mapper, name, cls)));
        }

        outputs.Add(("src/Ocsf/Generated/OcsfJsonContext.g.cs", EmitJsonContext(schema)));
        outputs.Add(("src/Ocsf/Generated/OcsfEventReader.g.cs", EmitEventReader(schema)));

        outputs.Add(("src/Ocsf.Validation/Generated/OcsfSchemaRegistry.Core.g.cs", EmitRegistryCore(schema)));
        outputs.Add(("src/Ocsf.Validation/Generated/OcsfSchemaRegistry.Objects.g.cs", EmitRegistryObjects(schema, mapper)));
        outputs.Add(("src/Ocsf.Validation/Generated/OcsfSchemaRegistry.Classes.g.cs", EmitRegistryClasses(schema, mapper)));

        return outputs;
    }

    private static void WriteRegistryFileHeader(CodeWriter w, ExportSchema schema)
    {
        w.WriteLine("// <auto-generated/>");
        w.WriteLine($"// Generated by Ocsf.Generator from the OCSF {schema.Version} schema export. Do not edit.");
        w.WriteLine();
        w.WriteLine("#nullable enable");
        w.WriteLine();
        w.WriteLine("namespace Ocsf.Validation;");
        w.WriteLine();
    }

    private static string EmitRegistryCore(ExportSchema schema)
    {
        var w = new CodeWriter();
        WriteRegistryFileHeader(w, schema);
        w.WriteLine("public static partial class OcsfSchemaRegistry");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("/// <summary>The OCSF schema version this registry was generated from.</summary>");
        w.WriteLine($"public const string SchemaVersion = \"{schema.Version}\";");
        w.WriteLine();

        w.WriteLine("private static IReadOnlyDictionary<string, TypeConstraint> BuildTypes()");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"var types = new Dictionary<string, TypeConstraint>({schema.Types.Count}, StringComparer.Ordinal);");
        foreach (var (name, type) in schema.Types.OrderBy(t => t.Key, StringComparer.Ordinal))
        {
            var maxLen = type.MaxLen?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "null";
            var regex = type.Regex is null ? "null" : DocFormatter.CSharpStringLiteral(type.Regex);
            var min = type.Range is { Count: 2 } ? type.Range[0] + "L" : "null";
            var max = type.Range is { Count: 2 } ? type.Range[1] + "L" : "null";
            var stringValues = type.Values is { Count: > 0 } values
                && values.All(v => v.ValueKind == System.Text.Json.JsonValueKind.String)
                ? "new[] { " + string.Join(", ", values.Select(v => DocFormatter.CSharpStringLiteral(v.GetString()!))) + " }"
                : "null";
            w.WriteLine($"types[\"{name}\"] = new(\"{name}\", {maxLen}, {regex}, {min}, {max}, {stringValues});");
        }
        w.WriteLine("return types;");
        w.Dedent();
        w.WriteLine("}");
        w.WriteLine();

        var profiles = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var cls in schema.Classes.Values)
            profiles.UnionWith(cls.Profiles ?? []);
        foreach (var obj in schema.Objects.Values)
            profiles.UnionWith(obj.Profiles ?? []);
        foreach (var attr in schema.Classes.Values.SelectMany(c => c.Attributes.Values)
                     .Concat(schema.Objects.Values.SelectMany(o => o.Attributes.Values))
                     .Concat(schema.BaseEvent.Attributes.Values))
        {
            if (attr.Profile is { Length: > 0 })
                profiles.Add(attr.Profile);
        }

        w.WriteLine("private static IReadOnlyCollection<string> BuildProfiles() => new HashSet<string>(StringComparer.Ordinal)");
        w.WriteLine("{");
        w.Indent();
        foreach (var profile in profiles)
            w.WriteLine($"\"{profile}\",");
        w.Dedent();
        w.WriteLine("};");
        w.Dedent();
        w.WriteLine("}");
        return w.ToString();
    }

    private static string EmitRegistryObjects(ExportSchema schema, TypeMapper mapper)
    {
        var w = new CodeWriter();
        WriteRegistryFileHeader(w, schema);
        w.WriteLine("public static partial class OcsfSchemaRegistry");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("private static IReadOnlyDictionary<string, ObjectSpec> BuildObjects()");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"var objects = new Dictionary<string, ObjectSpec>({schema.Objects.Count}, StringComparer.Ordinal);");
        foreach (var name in schema.Objects.Keys.OrderBy(k => k, StringComparer.Ordinal))
            w.WriteLine($"objects[\"{name}\"] = Object_{name}();");
        w.WriteLine("return objects;");
        w.Dedent();
        w.WriteLine("}");

        foreach (var (name, obj) in schema.Objects.OrderBy(o => o.Key, StringComparer.Ordinal))
        {
            w.WriteLine();
            w.WriteLine($"private static ObjectSpec Object_{name}() => new(");
            w.Indent();
            w.WriteLine($"\"{name}\",");
            WriteAttributeSpecs(w, mapper, obj.Attributes);
            WriteConstraintSpecs(w, obj.Constraints);
            w.WriteLine($"{DeprecatedSinceLiteral(obj.Deprecated)});");
            w.Dedent();
        }

        w.Dedent();
        w.WriteLine("}");
        return w.ToString();
    }

    private static string EmitRegistryClasses(ExportSchema schema, TypeMapper mapper)
    {
        var w = new CodeWriter();
        WriteRegistryFileHeader(w, schema);
        w.WriteLine("public static partial class OcsfSchemaRegistry");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("private static IReadOnlyDictionary<int, ClassSpec> BuildClasses()");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"var classes = new Dictionary<int, ClassSpec>({schema.Classes.Count});");
        foreach (var (name, cls) in schema.Classes.OrderBy(c => c.Value.Uid))
            w.WriteLine($"classes[{cls.Uid}] = Class_{name}();");
        w.WriteLine("return classes;");
        w.Dedent();
        w.WriteLine("}");

        foreach (var (name, cls) in schema.Classes.OrderBy(c => c.Key, StringComparer.Ordinal))
        {
            w.WriteLine();
            w.WriteLine($"private static ClassSpec Class_{name}() => new(");
            w.Indent();
            w.WriteLine($"\"{name}\", {DocFormatter.CSharpStringLiteral(cls.Caption ?? name)}, {cls.Uid}, {cls.CategoryUid},");
            WriteAttributeSpecs(w, mapper, cls.Attributes);
            WriteConstraintSpecs(w, cls.Constraints);
            w.WriteLine($"{DeprecatedSinceLiteral(cls.Deprecated)});");
            w.Dedent();
        }

        w.Dedent();
        w.WriteLine("}");
        return w.ToString();
    }

    private static void WriteAttributeSpecs(CodeWriter w, TypeMapper mapper, Dictionary<string, SchemaAttribute> attributes)
    {
        w.WriteLine("new AttributeSpec[]");
        w.WriteLine("{");
        w.Indent();
        foreach (var (attrName, attr) in attributes.OrderBy(a => a.Key, StringComparer.Ordinal))
        {
            var (kind, objectType) = AttrKindFor(mapper, attr);
            var scalarType = attr.Type is null or "object_t" ? "null" : $"\"{attr.Type}\"";
            var objectTypeLiteral = objectType is null ? "null" : $"\"{objectType}\"";
            var isArray = attr.IsArray ? "true" : "false";
            var requirement = "OcsfRequirement." + MapRequirement(attr.Requirement);
            var profile = attr.Profile is { Length: > 0 } ? $"\"{attr.Profile}\"" : "null";
            var sibling = attr.Sibling is { Length: > 0 } ? $"\"{attr.Sibling}\"" : "null";

            var enumMembers = "null";
            var deprecatedValues = "null";
            // String-keyed enums (e.g. cvss.depth) have no integer codes to check.
            if (attr.Enum is { Count: > 0 }
                && attr.Enum.Keys.All(k => long.TryParse(k, System.Globalization.CultureInfo.InvariantCulture, out _)))
            {
                var ordered = attr.Enum
                    .Select(kv => (Value: long.Parse(kv.Key, System.Globalization.CultureInfo.InvariantCulture), kv.Value.Caption, kv.Value.Deprecated))
                    .OrderBy(m => m.Value)
                    .ToList();
                enumMembers = "new Dictionary<long, string> { "
                    + string.Join(", ", ordered.Select(m => $"[{m.Value}] = {DocFormatter.CSharpStringLiteral(m.Caption)}"))
                    + " }";
                var deprecated = ordered.Where(m => m.Deprecated is not null).Select(m => m.Value).ToList();
                if (deprecated.Count > 0)
                    deprecatedValues = "new long[] { " + string.Join(", ", deprecated) + " }";
            }

            w.WriteLine($"new(\"{attrName}\", AttrKind.{kind}, {scalarType}, {objectTypeLiteral}, {isArray}, "
                + $"{requirement}, {profile}, {sibling}, {enumMembers}, {deprecatedValues}, {DeprecatedSinceLiteral(attr.Deprecated)}),");
        }
        w.Dedent();
        w.WriteLine("},");
    }

    private static void WriteConstraintSpecs(CodeWriter w, Dictionary<string, List<string>>? constraints)
    {
        var known = (constraints ?? [])
            .Where(c => c.Key is "at_least_one" or "just_one" && c.Value.Count > 0)
            .OrderBy(c => c.Key, StringComparer.Ordinal)
            .ToList();
        if (known.Count == 0)
        {
            w.WriteLine("Array.Empty<SchemaConstraint>(),");
            return;
        }

        w.WriteLine("new SchemaConstraint[]");
        w.WriteLine("{");
        w.Indent();
        foreach (var (kind, attrs) in known)
        {
            var kindName = kind == "at_least_one" ? "AtLeastOne" : "JustOne";
            var names = string.Join(", ", attrs.OrderBy(a => a, StringComparer.Ordinal).Select(a => $"\"{a}\""));
            w.WriteLine($"new(ConstraintKind.{kindName}, new[] {{ {names} }}),");
        }
        w.Dedent();
        w.WriteLine("},");
    }

    private static (string Kind, string? ObjectType) AttrKindFor(TypeMapper mapper, SchemaAttribute attr)
    {
        if (attr.Type == "object_t")
        {
            return attr.ObjectType is null or "object" || attr.ObjectType.Contains('/')
                ? ("Json", null)
                : ("Object", attr.ObjectType);
        }

        if (attr.Type == "datetime_t")
            return ("Datetime", null);

        return mapper.MapScalar(attr.Type!) switch
        {
            "string" => ("String", null),
            "int" => ("Integer", null),
            "long" => ("Long", null),
            "double" => ("Float", null),
            "bool" => ("Boolean", null),
            "OcsfTimestamp" => ("Timestamp", null),
            "JsonElement" => ("Json", null),
            var other => throw new InvalidOperationException($"Unmapped scalar '{other}' for attribute kind."),
        };
    }

    private static string DeprecatedSinceLiteral(SchemaDeprecation? deprecation) =>
        deprecation is null ? "null" : DocFormatter.CSharpStringLiteral(deprecation.Since ?? "");

    /// <summary>Fully qualified C# type name of an event class.</summary>
    private static string EventTypeName(SchemaClass cls) =>
        $"Events.{CategoryNamespace(cls.Category)}.{NameMapper.PascalCase(cls.Name)}";

    private static string EmitJsonContext(ExportSchema schema)
    {
        var w = new CodeWriter();
        WriteFileHeader(w, schema);
        w.WriteLine("#pragma warning disable CS0618 // deprecated classes stay serializable");
        w.WriteLine();
        w.WriteLine("namespace Ocsf;");
        w.WriteLine();
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Source-generated serializer context covering every OCSF event class and object,");
        w.WriteLine("/// enabling reflection-free serialization under NativeAOT and trimming.");
        w.WriteLine("/// </summary>");
        w.WriteLine("[JsonSourceGenerationOptions(");
        w.Indent();
        w.WriteLine("DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        w.WriteLine("Converters = new[] { typeof(Converters.OcsfTimestampConverter) })]");
        w.Dedent();

        foreach (var (_, cls) in schema.Classes.OrderBy(c => c.Key, StringComparer.Ordinal))
            w.WriteLine($"[JsonSerializable(typeof({EventTypeName(cls)}))]");
        foreach (var name in schema.Objects.Keys.OrderBy(k => k, StringComparer.Ordinal))
            w.WriteLine($"[JsonSerializable(typeof(Objects.{NameMapper.PascalCase(name)}))]");

        w.WriteLine("public partial class OcsfJsonContext : JsonSerializerContext");
        w.WriteLine("{");
        w.WriteLine("}");
        return w.ToString();
    }

    private static string EmitEventReader(ExportSchema schema)
    {
        var w = new CodeWriter();
        WriteFileHeader(w, schema);
        w.WriteLine("#pragma warning disable CS0618 // deprecated classes stay deserializable");
        w.WriteLine();
        w.WriteLine("namespace Ocsf;");
        w.WriteLine();
        w.WriteLine("/// <summary>Deserializes OCSF events to their typed event class by <c>class_uid</c>.</summary>");
        w.WriteLine("public static class OcsfEventReader");
        w.WriteLine("{");
        w.Indent();

        var byUid = schema.Classes.Values.OrderBy(c => c.Uid).ToList();

        w.WriteLine("/// <summary>Deserializes an OCSF event, dispatching on its <c>class_uid</c>.");
        w.WriteLine("/// Returns null when <c>class_uid</c> is missing or not a known event class.</summary>");
        w.WriteLine("public static OcsfEvent? Deserialize(string json)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("using var document = JsonDocument.Parse(json);");
        w.WriteLine("return Deserialize(document.RootElement);");
        w.Dedent();
        w.WriteLine("}");
        w.WriteLine();

        w.WriteLine("/// <summary>Deserializes an OCSF event, dispatching on its <c>class_uid</c>.");
        w.WriteLine("/// Returns null when <c>class_uid</c> is missing or not a known event class.</summary>");
        w.WriteLine("public static OcsfEvent? Deserialize(JsonElement element)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (element.ValueKind != JsonValueKind.Object");
        w.WriteLine("    || !element.TryGetProperty(\"class_uid\", out var uid)");
        w.WriteLine("    || uid.ValueKind != JsonValueKind.Number");
        w.WriteLine("    || !uid.TryGetInt32(out var classUid))");
        w.Indent();
        w.WriteLine("return null;");
        w.Dedent();
        w.WriteLine();
        w.WriteLine("return classUid switch");
        w.WriteLine("{");
        w.Indent();
        foreach (var cls in byUid)
            w.WriteLine($"{cls.Uid} => element.Deserialize(OcsfJsonContext.Default.{NameMapper.PascalCase(cls.Name)}),");
        w.WriteLine("_ => null,");
        w.Dedent();
        w.WriteLine("};");
        w.Dedent();
        w.WriteLine("}");
        w.WriteLine();

        w.WriteLine("/// <summary>Returns the generated CLR type for a <c>class_uid</c>, or null if unknown.</summary>");
        w.WriteLine("public static Type? GetEventType(int classUid) => classUid switch");
        w.WriteLine("{");
        w.Indent();
        foreach (var cls in byUid)
            w.WriteLine($"{cls.Uid} => typeof({EventTypeName(cls)}),");
        w.WriteLine("_ => null,");
        w.Dedent();
        w.WriteLine("};");

        w.Dedent();
        w.WriteLine("}");
        return w.ToString();
    }

    /// <summary>Category namespace segment. "system" is renamed to avoid clashing with the
    /// System namespace in consumer code.</summary>
    internal static string CategoryNamespace(string? category) => category switch
    {
        null or "" or "other" => "Other",
        "system" => "SystemActivity",
        _ => NameMapper.PascalCase(category),
    };

    private static string EmitObject(ExportSchema schema, TypeMapper mapper, string name, SchemaObject obj)
    {
        var w = new CodeWriter();
        var className = NameMapper.PascalCase(name);
        WriteFileHeader(w, schema);
        w.WriteLine("namespace Ocsf.Objects;");
        w.WriteLine();

        var enums = new List<EnumDecl>();

        w.WriteDocSummary(BuildTypeDoc(obj.Caption, obj.Description, $"OCSF object <c>{name}</c>."));
        WriteObsolete(w, obj.Deprecated);
        w.WriteLine($"[OcsfObject(\"{name}\")]");
        w.WriteLine($"public class {className} : OcsfObject");
        w.WriteLine("{");
        w.Indent();
        WriteAttributeProperties(w, schema, mapper, className, obj.Attributes, enums, EmitTarget.Object, objectPrefix: "");
        w.Dedent();
        w.WriteLine("}");

        WriteEnumDecls(w, enums);
        return w.ToString();
    }

    private static string EmitBaseEvent(ExportSchema schema, TypeMapper mapper)
    {
        var w = new CodeWriter();
        WriteFileHeader(w, schema);
        w.WriteLine("namespace Ocsf;");
        w.WriteLine();

        var enums = new List<EnumDecl>();

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Attributes shared by all OCSF event classes, from the base_event definition.");
        w.WriteLine("/// Enum-coded attributes (activity_id, severity_id, ...) are declared on each");
        w.WriteLine("/// concrete class with class-specific enum types.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public abstract partial class OcsfEvent");
        w.WriteLine("{");
        w.Indent();
        WriteAttributeProperties(w, schema, mapper, "OcsfEvent", schema.BaseEvent.Attributes, enums,
            EmitTarget.BaseEvent, objectPrefix: "Objects.");
        w.Dedent();
        w.WriteLine("}");

        if (enums.Count > 0)
            throw new InvalidOperationException("base_event emission must not produce enum declarations.");
        return w.ToString();
    }

    private static string EmitEventClass(ExportSchema schema, TypeMapper mapper, string name, SchemaClass cls)
    {
        var w = new CodeWriter();
        var className = NameMapper.PascalCase(name);
        WriteFileHeader(w, schema);
        w.WriteLine($"namespace Ocsf.Events.{CategoryNamespace(cls.Category)};");
        w.WriteLine();

        var enums = new List<EnumDecl>();

        w.WriteDocSummary(BuildTypeDoc(cls.Caption, cls.Description, $"OCSF event class <c>{name}</c>."));
        WriteObsolete(w, cls.Deprecated);
        w.WriteLine($"[OcsfEventClass({cls.Uid}, {cls.CategoryUid}, \"{name}\")]");
        w.WriteLine($"public class {className} : OcsfEvent");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"/// <summary>The <c>class_uid</c> of the <c>{name}</c> event class.</summary>");
        w.WriteLine($"public const int EventClassUid = {cls.Uid};");
        w.WriteLine();
        w.WriteLine($"/// <summary>The <c>category_uid</c> of the <c>{name}</c> event class.</summary>");
        w.WriteLine($"public const int EventCategoryUid = {cls.CategoryUid};");
        w.WriteLine();

        w.WriteLine("/// <summary>Initializes the classification attributes to this class's identity.</summary>");
        w.WriteLine($"public {className}()");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("ClassUid = EventClassUid;");
        w.WriteLine("CategoryUid = EventCategoryUid;");
        w.WriteLine("TypeUid = EventClassUid * 100L;");
        if (cls.Caption is { Length: > 0 })
            w.WriteLine($"ClassName = {DocFormatter.CSharpStringLiteral(cls.Caption)};");
        if (cls.CategoryName is { Length: > 0 })
            w.WriteLine($"CategoryName = {DocFormatter.CSharpStringLiteral(cls.CategoryName)};");
        w.Dedent();
        w.WriteLine("}");

        WriteAttributeProperties(w, schema, mapper, className, cls.Attributes, enums,
            EmitTarget.EventClass, objectPrefix: "Objects.", leadingBlankLine: true);

        if (enums.Any(e => e.Name == className + "ActivityId"))
        {
            w.WriteLine();
            w.WriteLine("/// <summary>Sets <c>activity_id</c> and recomputes <c>type_uid</c> accordingly.</summary>");
            w.WriteLine($"public void SetActivity({className}ActivityId activity)");
            w.WriteLine("{");
            w.Indent();
            w.WriteLine("ActivityId = activity;");
            w.WriteLine("TypeUid = EventClassUid * 100L + (long)activity;");
            w.Dedent();
            w.WriteLine("}");
        }

        w.Dedent();
        w.WriteLine("}");

        WriteEnumDecls(w, enums);
        return w.ToString();
    }

    internal static void WriteFileHeader(CodeWriter w, ExportSchema schema)
    {
        w.WriteLine("// <auto-generated/>");
        w.WriteLine($"// Generated by Ocsf.Generator from the OCSF {schema.Version} schema export. Do not edit.");
        w.WriteLine();
        w.WriteLine("#nullable enable");
        w.WriteLine();
        w.WriteLine("using System.Text.Json;");
        w.WriteLine("using System.Text.Json.Serialization;");
        w.WriteLine();
    }

    internal static string BuildTypeDoc(string? caption, string? description, string fallback)
    {
        var text = description is { Length: > 0 } ? DocFormatter.ToXmlDocText(description) : fallback;
        return caption is { Length: > 0 } ? $"{DocFormatter.ToXmlDocText(caption)}.\n{text}" : text;
    }

    internal static void WriteObsolete(CodeWriter w, SchemaDeprecation? deprecation)
    {
        if (deprecation is null)
            return;
        var message = deprecation.Message is { Length: > 0 }
            ? DocFormatter.ToPlainText(deprecation.Message)
            : "Deprecated in the OCSF schema.";
        if (deprecation.Since is { Length: > 0 })
            message += $" Deprecated since {deprecation.Since}.";
        w.WriteLine($"[Obsolete({DocFormatter.CSharpStringLiteral(message)})]");
    }

    internal static void WriteAttributeProperties(
        CodeWriter w,
        ExportSchema schema,
        TypeMapper mapper,
        string ownerPascal,
        Dictionary<string, SchemaAttribute> attributes,
        List<EnumDecl> enums,
        EmitTarget target,
        string objectPrefix,
        bool leadingBlankLine = false)
    {
        var usedNames = new HashSet<string>(StringComparer.Ordinal) { ownerPascal };
        var first = !leadingBlankLine;

        foreach (var (attrName, attr) in attributes.OrderBy(a => a.Key, StringComparer.Ordinal))
        {
            if (SkipAttribute(schema, attrName, attr, target))
                continue;

            if (!first)
                w.WriteLine();
            first = false;

            var propName = NameMapper.PascalCase(attrName);
            if (propName == ownerPascal)
                propName += "Value";
            if (!usedNames.Add(propName))
                throw new InvalidOperationException($"Duplicate property name '{propName}' in '{ownerPascal}'.");

            var baseType = ResolvePropertyType(schema, mapper, ownerPascal, attrName, attr, enums, target, objectPrefix);
            var fullType = attr.IsArray ? $"List<{baseType}>?" : baseType + "?";

            w.WriteDocSummary(BuildAttributeDoc(attrName, attr));
            WriteObsolete(w, attr.Deprecated);
            w.WriteLine($"[JsonPropertyName(\"{attrName}\")]");
            w.WriteLine("[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
            w.WriteLine($"[OcsfRequirement(OcsfRequirement.{MapRequirement(attr.Requirement)})]");
            w.WriteLine($"public {fullType} {NameMapper.Identifier(propName)} {{ get; set; }}");
        }
    }

    private static bool SkipAttribute(ExportSchema schema, string attrName, SchemaAttribute attr, EmitTarget target)
    {
        switch (target)
        {
            case EmitTarget.BaseEvent:
                // Enum-coded attributes vary by class, so the shared base declares only
                // the non-enum ones. Classification attributes are numbers by design.
                return attr.Enum is { Count: > 0 } && !ClassificationAttrs.Contains(attrName);

            case EmitTarget.EventClass:
                if (ClassificationAttrs.Contains(attrName))
                    return true;
                if (!schema.BaseEvent.Attributes.TryGetValue(attrName, out var baseAttr))
                    return false;
                // Inherited only when base_event declares it with the same wire shape and
                // neither side is enum-coded (enum attributes always live on the class).
                return baseAttr.Type == attr.Type
                    && baseAttr.IsArray == attr.IsArray
                    && baseAttr.ObjectType == attr.ObjectType
                    && attr.Enum is null
                    && baseAttr.Enum is null;

            default:
                return false;
        }
    }

    private static string ResolvePropertyType(
        ExportSchema schema,
        TypeMapper mapper,
        string ownerPascal,
        string attrName,
        SchemaAttribute attr,
        List<EnumDecl> enums,
        EmitTarget target,
        string objectPrefix)
    {
        var ocsfType = attr.Type
            ?? throw new InvalidOperationException($"Attribute '{ownerPascal}.{attrName}' has no type.");

        if (ocsfType == "object_t")
        {
            // References to objects missing from the export (extension objects like
            // win/win_service reachable from core attributes) stay untyped.
            if (attr.ObjectType is null or "object" || attr.ObjectType.Contains('/'))
                return "JsonElement";
            if (!schema.Objects.ContainsKey(attr.ObjectType))
                throw new InvalidOperationException(
                    $"Attribute '{ownerPascal}.{attrName}' references unknown object '{attr.ObjectType}'.");
            return objectPrefix + NameMapper.PascalCase(attr.ObjectType);
        }

        // Integer-backed enums become C# enums; string-backed enums stay strings.
        // Classification attributes keep their numeric type: their single-value enums
        // express class identity, which is exposed via constants instead.
        if (attr.Enum is { Count: > 0 }
            && !ClassificationAttrs.Contains(attrName)
            && target != EmitTarget.BaseEvent
            && mapper.IsIntegerBased(ocsfType))
        {
            var enumName = ownerPascal + NameMapper.PascalCase(attrName);
            if (enums.All(e => e.Name != enumName))
                enums.Add(BuildEnumDecl(enumName, attrName, attr));
            return enumName;
        }

        return mapper.MapScalar(ocsfType);
    }

    private static EnumDecl BuildEnumDecl(string enumName, string attrName, SchemaAttribute attr)
    {
        var used = new HashSet<string>(StringComparer.Ordinal);
        var members = attr.Enum!
            .Select(kv => (Value: long.Parse(kv.Key, System.Globalization.CultureInfo.InvariantCulture), Member: kv.Value))
            .OrderBy(m => m.Value)
            .Select(m => new EnumMemberDecl(
                m.Value,
                NameMapper.EnumMemberName(m.Member.Caption, m.Value.ToString(System.Globalization.CultureInfo.InvariantCulture), used),
                m.Member.Description,
                m.Member.Deprecated))
            .ToList();

        var doc = $"Values for the <c>{attrName}</c> attribute.";
        if (attr.Sibling is { Length: > 0 })
            doc += $"\nWhen the value is <c>Other</c> (99), the <c>{attr.Sibling}</c> attribute contains the source-specific label.";
        return new EnumDecl(enumName, doc, members);
    }

    internal static void WriteEnumDecls(CodeWriter w, List<EnumDecl> enums)
    {
        foreach (var decl in enums.OrderBy(e => e.Name, StringComparer.Ordinal))
        {
            w.WriteLine();
            w.WriteDocSummary(decl.Doc);
            w.WriteLine($"public enum {decl.Name}");
            w.WriteLine("{");
            w.Indent();
            foreach (var member in decl.Members)
            {
                if (member.Description is { Length: > 0 })
                    w.WriteDocSummary(DocFormatter.ToXmlDocText(member.Description));
                WriteObsolete(w, member.Deprecated);
                w.WriteLine($"{member.Name} = {member.Value},");
            }
            w.Dedent();
            w.WriteLine("}");
        }
    }

    private static string BuildAttributeDoc(string attrName, SchemaAttribute attr)
    {
        var text = attr.Description is { Length: > 0 }
            ? DocFormatter.ToXmlDocText(attr.Description)
            : DocFormatter.ToXmlDocText(attr.Caption ?? attrName);

        var notes = new List<string>();
        if (attr.Requirement is "required" or "recommended")
            notes.Add($"Requirement: {attr.Requirement}.");
        if (attr.Profile is { Length: > 0 })
            notes.Add($"Part of the <c>{attr.Profile}</c> profile.");
        if (attr.Sibling is { Length: > 0 } && attr.Enum is { Count: > 0 })
            notes.Add($"Sibling label attribute: <c>{attr.Sibling}</c>.");

        return notes.Count == 0 ? text : $"{text}\n{string.Join(' ', notes)}";
    }

    private static string MapRequirement(string? requirement) => requirement switch
    {
        "required" => "Required",
        "recommended" => "Recommended",
        _ => "Optional",
    };
}

internal sealed record EnumDecl(string Name, string Doc, List<EnumMemberDecl> Members);

internal sealed record EnumMemberDecl(long Value, string Name, string? Description, SchemaDeprecation? Deprecated);
